map-egypt/map-egypt.github.io

- package.json
- test/components/app.js
> Include react-dom

- app/assets/scripts/actions/index.js
- app/assets/scripts/config/production.js
- app/assets/scripts/main.js
- app/assets/scripts/utils/auth.js
- package.json
Include the relevant actions and trigger them in `main.js`.
> Add queries for indicators and projects

- app/assets/scripts/config/production.js
Add api url. Originally had this in `local.js` but there's no reason it shouldn't be checked into the repo.
> Include new api url

- app/assets/scripts/components/charts/horizontal-bar.js
- app/assets/scripts/components/charts/pie.js
- app/assets/scripts/utils/date.js
- app/assets/scripts/utils/slugify.js
- app/assets/scripts/views/home.js
- app/assets/styles/components/_charts.scss
- app/assets/styles/main.scss
- test/actions.js
- test/util/date.js
Need styling cc @ascalamogna but code-wise these should be ready for review & merge @kamicut
> Bar & circle charts for home view

- app/assets/scripts/components/page-header.js
- app/assets/scripts/main.js
- app/assets/scripts/views/app.js
- app/assets/scripts/views/uhoh.js
- app/assets/styles/core/_inpages.scss
- app/assets/styles/core/_uhoh.scss
- app/assets/styles/main.scss
@dereklieu this still needs the header and footer added to it. Also I noticed the URL doesn't contain a language and I think we'll want this in arabic too?
> styles for 404 page

- app/assets/scripts/actions/index.js
- app/assets/scripts/components/charts/vertical-bar.js
- app/assets/scripts/components/project-card.js
- app/assets/scripts/components/project-timeline.js
- app/assets/scripts/components/share.js
- app/assets/scripts/config.js
- app/assets/scripts/config/develop.js
- app/assets/scripts/main.js
- app/assets/scripts/reducers/api.js
- app/assets/scripts/utils/date.js
- app/assets/scripts/utils/format.js
- app/assets/scripts/views/home.js
- app/assets/scripts/views/project-browse.js
- app/assets/scripts/views/project.js
- app/assets/styles/components/_charts.scss
- app/assets/styles/core/_cards.scss
- package.json
Hooks up the majority of the project page, including timeline, KMI indicators, overview card.
Missing the Project Comparison and Related Projects features, but will fill those in separately.
> Project detail

- app/assets/scripts/components/charts/horizontal-bar.js
- app/assets/scripts/components/project-card.js
- app/assets/scripts/utils/format.js
- app/assets/scripts/views/project.js
Includes the rest of the charts for the project page, except for the reach charts which we don't have data for yet.
@kamicut assigning this to you.
> Finish project page

- app/assets/scripts/components/project-list.js
- app/assets/scripts/views/project-browse.js
This adds functionality to the project-view toggle button. Closes #34
> Project View toggle

- app/assets/scripts/views/donor.js
This adds basic data to the donor page. We don't have the data yet for disbursed funds, which we'll need to create an "amounts remaining" stat and chart. @dereklieu for review.
> 45 donor page

- app/assets/scripts/components/charts/axis.js
- app/assets/scripts/components/charts/horizontal-bar.js
- app/assets/scripts/views/project.js
- app/assets/styles/components/_charts.scss
Close #47 
Close #46 
@kamicut can you give this a 👀 and merge if it's 👍
> Format axis ticks

- .build_scripts/deploy.sh
Sorry @dereklieu, used the wrong reference last time
> Correct branch ref

- app/assets/scripts/components/charts/horizontal-bar.js
- app/assets/scripts/components/charts/vertical-bar.js
- app/assets/scripts/components/map.js
- app/assets/scripts/components/page-footer.js
- app/assets/scripts/components/project-card.js
- app/assets/scripts/views/category.js
- app/assets/scripts/views/project-browse.js
- app/assets/scripts/views/project.js
- app/assets/styles/components/_buttons.scss
- app/assets/styles/components/_charts.scss
- app/assets/styles/components/_drops.scss
- app/assets/styles/components/_forms.scss
- app/assets/styles/components/_modals.scss
- app/assets/styles/core/_browse.scss
- app/assets/styles/core/_cards.scss
- app/assets/styles/core/_donor.scss
- app/assets/styles/core/_footer.scss
- app/assets/styles/core/_home.scss
- app/assets/styles/core/_inpages.scss
- app/assets/styles/core/_map.scss
- app/assets/styles/core/_projects.scss
- app/assets/styles/core/_tables.scss
- app/assets/styles/core/_typography.scss
@dereklieu these are all the fixes to every issues assigned to me.
> Style fixes

- package.json
> Remove topojson deps

- app/assets/scripts/components/map.js
- app/assets/scripts/components/page-header.js
- app/assets/scripts/components/project-card.js
- app/assets/scripts/components/share.js
- app/assets/scripts/main.js
- app/assets/scripts/utils/date.js
- app/assets/scripts/utils/format.js
- app/assets/scripts/views/home.js
- app/assets/scripts/views/project-browse.js
- app/assets/scripts/views/project.js
- package.json
Takes care of a lot of smaller ticket items.
Over to @kamicut to review and merge.
> Small fixes

- app/assets/scripts/components/charts/axis.js
- app/assets/scripts/components/charts/horizontal-bar.js
- app/assets/scripts/components/charts/vertical-bar.js
- app/assets/scripts/views/project.js
Add support for multilingual disbursement charts.
Fix bug where a project page wouldn't load a new project when you clicked on it.
> Fix logged in charts

- app/assets/scripts/components/project-list.js
- app/assets/scripts/views/project-browse.js
- app/assets/scripts/views/project.js
- app/assets/styles/core/_map.scss
> Finish project list

- app/assets/scripts/components/charts/axis.js
> Use width for chart axis

- app/assets/scripts/components/project-timeline.js
Shows progress at current date for projects where no actual end date is specified
> Updates project timeline for active projects

- app/assets/scripts/views/project-browse.js
- app/assets/scripts/views/project.js
> Additional project filters

- app/assets/scripts/views/ministry.js
- app/assets/scripts/views/project-browse.js
- app/assets/scripts/views/project.js
- app/assets/styles/components/_charts.scss
- app/assets/styles/components/_modals.scss
- app/assets/styles/core/_browse.scss
- app/assets/styles/core/_cards.scss
- app/assets/styles/core/_home.scss
- app/assets/styles/core/_inpages.scss
- app/assets/styles/core/_map.scss
- app/assets/styles/core/_rtl.scss
- app/assets/styles/vendor/_marker-cluster.scss
closes #169, closes #175, closes #183, closes #160, closes #120, closes #162, closes #181
> design fixes

- app/assets/scripts/components/map.js
- app/assets/scripts/components/project-card.js
- app/assets/scripts/utils/map-utils.js
Fix #172 
Implement project markers on tooltips to partially close #163. 
@ascalamogna I noticed that all through the site it seems the on-time/delayed markers aren't showing the right color though the text is now working. Can I pass this on to you?
> Map markers

- app/assets/scripts/components/page-footer.js
@felskia this implements email signup on the frontend. Right now it sends the email from marc@developmentseed.org but we can change that in the admin panel once we know the details of the contact information.
> Add email signup functionality

- app/assets/scripts/components/page-header.js
- app/assets/styles/components/_charts.scss
- app/assets/styles/core/_prime-nav.scss
> Style tweaks

- app/assets/scripts/actions/index.js
- app/assets/scripts/components/map.js
- app/assets/scripts/components/page-footer.js
- app/assets/scripts/main.js
- app/assets/scripts/reducers/api.js
- app/assets/scripts/utils/map-utils.js
- app/assets/scripts/views/project-browse.js
Maps district indicators.
Currently we have only one test indicator on districts. You can find this at:
Other Development Indicators -> Education & Training -> Test District
Over to @nbumbarger to review this PR and merge.
> Mapping district indicators

- app/assets/styles/core/_print.scss
- app/assets/styles/main.scss
- app/assets/styles/settings/_mixins.scss
@nbumbarger I added in the print styles here. I think they might need tweaked a bit once other things are fixed.
> add print styles

- app/assets/scripts/components/page-footer.js
- app/assets/scripts/views/home.js
Remove offending input. Close #214. 
I removed an input field and that solves the page disappearing issue. The email form still seems to work fine. @kamicut can you check this and merge?
> Fix arabic site

- app/assets/scripts/components/charts/axis.js
- app/assets/scripts/components/charts/horizontal-bar.js
- app/assets/scripts/components/page-header.js
- app/assets/scripts/views/category.js
- app/assets/scripts/views/donor.js
- app/assets/scripts/views/home.js
- app/assets/scripts/views/ministry.js
- app/assets/scripts/views/owner.js
- app/assets/scripts/views/project.js
To @nbumbarger to read over and merge.
> Reverse charts

- app/assets/scripts/components/print-btn.js
- app/assets/scripts/views/category.js
- app/assets/scripts/views/donor.js
- app/assets/scripts/views/project.js
> print button calls window.print

- app/assets/scripts/components/charts/vertical-bar.js
- app/assets/scripts/views/project.js
Close #240 
Add fund name to disbursement chart.
> Fix disbursement chart

- app/assets/scripts/config/production.js
Migrates application to map-egypt auth0 account.
> Migrate auth0

- app/assets/scripts/components/page-footer.js
- app/assets/scripts/views/project.js
- app/assets/styles/core/_rtl.scss
- app/assets/translations/ar.yml
- app/assets/translations/en.yml
There were some rtl issues throughout and then just fixed a few text things that Hagar wanted fixed. 
Closes: #247 and #246
The bigger thing here is that when I was in local host I was having log in issues. What I did was: 
- went straight into Arabic from the homepage
- went to a project 
- clicked on log in, and logged in
- (logged me in but didn't give me the data that was supposed to be on the page)
- When I clicked on a related project at the bottom, it only gave me the header and footer of the page. 
Also, here was the error I was getting:
> fixing small text issues and also right to left problems

- app/assets/scripts/components/map.js
- app/assets/scripts/utils/districts.js
- app/assets/scripts/utils/map-utils.js
@nbumbarger to review and merge.
> Clean up district vs governorate distinction helper

- app/assets/scripts/components/map.js
@dereklieu don't know if you want to check this out as well or not. If not just let me know and I'll push it.
> changed indicator colors

- app/assets/scripts/components/print-btn.js
- app/assets/scripts/views/ministry.js
- app/assets/scripts/views/owner.js
- app/assets/scripts/views/project.js
- app/assets/styles/core/_inpages.scss
- app/assets/styles/core/_rtl.scss
- app/assets/translations/ar.yml
- app/assets/translations/en.yml
Just some small styling changes and making sure the print button was on every page and labeled correctly.
> fixed download buttons and project status styles

- app/assets/scripts/components/csv-btn.js
... and are given the correct file extension in WIndows
> Ensure that CSVs are downloaded in Safari

- app/assets/scripts/views/project.js
- app/assets/styles/core/_inpages.scss
> fixed weird spacing when too many stats are showing

- app/assets/scripts/components/csv-btn.js
- app/assets/scripts/utils/serialize-csv.js
- app/assets/scripts/views/project-browse.js
> Add csv, print button to project list page

- app/assets/scripts/views/project-browse.js
- app/assets/styles/components/_drops.scss
- app/assets/styles/core/_print.scss
@dereklieu I updated the print stylesheets and took away the share since it doesn't do much on that page. Let me know what you think.
Thanks!
> revised buttons and updated print css

- app/assets/scripts/components/map.js
- app/assets/styles/core/_map.scss
> Add project count to cluster icons in map legend

- app/assets/scripts/components/project-timeline.js
- app/assets/scripts/utils/date.js
- app/assets/scripts/views/project.js
Defaulting to locale-based date format only works when the browser's locale is set. This fix forces Arabic date formatting when the Arabic view is turned on, regardless of user settings.
> close #313; force Arabic date format when in Arabic view

- app/assets/scripts/views/project.js
- app/assets/styles/core/_projects.scss
- app/assets/translations/ar.yml
- app/assets/translations/en.yml
Connects to extra fields that will be added through [API](https://github.com/map-egypt/api/pull/34) and [admin panel](https://github.com/map-egypt/admin/pull/110) additions.
> Add recommendations and contract date fields

- app/assets/graphics/collecticons/arrow-down.svg
- app/assets/graphics/collecticons/arrow-up.svg
- app/assets/scripts/components/project-list.js
- app/assets/scripts/views/project-browse.js
- app/assets/styles/components/_buttons.scss
- app/assets/styles/components/_dropdown.scss
- app/assets/styles/components/_drops.scss
- app/assets/styles/core/_rtl.scss
- app/assets/translations/ar.yml
- app/assets/translations/en.yml
Close #325
In addition to adding translation to the indicator and sorting dropdown, enables sorting of articles (alphabetical and ascending/descending by percentage completion).
> Sorting/ translation

- app/index.html
> Add IFPRI's Google Analytics code

- app/assets/scripts/components/map.js
> Reverse category labels

- app/assets/scripts/views/project-browse.js
- app/assets/translations/ar.yml
- app/assets/translations/en.yml
> Show arabic for project ontime/delayed

- app/assets/scripts/views/project-browse.js
> Alphabetize indicators

- app/assets/scripts/views/project-browse.js
- app/assets/translations/ar.yml
- app/assets/translations/en.yml
Uses arabic donor name.
Also adds the headers to the translation files (eg "Donor" and "SDG Goals"). Arabic needs to be changed cc @hagareldidi
> Use donor_name_ar, put headers in translation files

- app/assets/scripts/main.js
- app/assets/scripts/utils/auth.js
- package.json
Based on:
https://github.com/map-yemen/map-yemen.github.io/pull/58
https://github.com/map-yemen/map-yemen.github.io/pull/59
> Upgrade auth0 to v11
